AllCops:
  TargetRubyVersion: 2.5.1
  DisplayCopNames: true

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

Style/FormatStringToken:
  EnforcedStyle: template

Style/ParallelAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 15

Style/IndentationConsistency:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
